version: '3.8'

services:
  aiwife-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
