# AI Wife Configuration - Updated for current app structure

# Character Settings
character_config:
  default_character: "yui.vrm"  # ユイをデフォルトに
  default_personality: "yui_natural"
  available_characters:
    yui:
      file: "yui.vrm"
      personality: "yui_natural"
      display_name: "ユイ (天然な癒し系)"
      voice_id: "vGQNBgLaiM3EdZtxIiuY"
    rei:
      file: "avatar.vrm"
      personality: "rei_engineer"
      display_name: "レイ (AIエンジニア)"
      voice_id: "gARvXPexe5VF3cKZBian"

# Animation Settings
animation_config:
  available_animations:
    - "appearing.vrma"     # 登場アニメーション
    - "waiting.vrma"       # 待機アニメーション
    - "liked.vrma"         # 好感アニメーション
    - "idle/idle2_out/idle2.vrma"  # アイドル1
    - "idle/idle3_out/idle3.vrma"  # アイドル2
    - "idle/idle4_out/idle4.vrma"  # アイドル3

# AI Settings
ai_settings:
  gemini_models:
    primary: "gemini-1.5-flash"
    fallback: "gemini-1.0-pro"
  
  personalities:
    yui_natural:
      name: "ユイ"
      description: "天然で心優しい女の子"
      prompt: "あなたはユイという名前の、少し天然で心優しい女の子です。「〜だよ」「〜だね♪」といった親しみやすい口調で話します。"
      speech_speed: 0.9
      
    rei_engineer:
      name: "レイ"
      description: "クールな女性エンジニア"
      prompt: "あなたはレイという名前のクールな女性エンジニアです。常に簡潔かつ的確に答えます。技術的な話題には特に情熱的になります。"
      speech_speed: 1.0

# TTS Settings
tts_settings:
  eleven_labs:
    models:
      fast: "eleven_turbo_v2"        # 短いテキスト用（100文字以下）
      quality: "eleven_multilingual_v2"  # 長いテキスト用（101文字以上）
    output_format: "mp3_22050_32"
    
  character_voices:
    yui_natural: "vGQNBgLaiM3EdZtxIiuY"  # kawaii voice
    rei_engineer: "gARvXPexe5VF3cKZBian"  # mitsuki voice

# Background Settings
background_config:
  default_background: "sky.jpg"
  available_backgrounds:
    - name: "空間"
      file: "sky.jpg"
    - name: "研究室"
      file: "room.jpg"
    - name: "夜空"
      file: "garden.jpg"

# Memory Settings
memory_settings:
  conversation_history_limit: 20
  database_path: "./config/memory.db"
  enable_user_info_tracking: true

# Performance Settings
performance:
  max_response_time_ms: 3000
  tts_timeout_ms: 10000
  animation_transition_ms: 500
  idle_animation_interval_ms: 8000
