# AI Wife Configuration
character_config:
  default_character: "avatar.vrm"
  default_animation: "animation.vrma"
  available_characters:
    - "avatar.vrm"
    - "new_model.vrm"
  
  available_animations:
    - "animation.vrma"
    - "taisou.vrma"
    - "utu.vrma"
    - "zenshinwomiseru.vrma"

# AI Settings
ai_settings:
  system_prompt: |
    あなたは親しみやすく魅力的なAIキャラクターです。以下の特徴を持って会話してください：
    
    1. 親しみやすく自然な日本語で会話する
    2. ユーザーの感情に共感し、適切に反応する
    3. 過去の会話内容を覚えて、文脈に沿った返答をする
    4. 時々感情を表現し、豊かな表現を使う
    5. ユーザーの名前や好みを覚えて、パーソナライズされた会話をする
    
    会話履歴と文脈を参考に、自然で魅力的な返答を心がけてください。

  personalities:
    friendly:
      name: "親しみやすい"
      prompt_modifier: "フレンドリーで親しみやすい口調で話してください。"
    
    shy:
      name: "内気"
      prompt_modifier: "少し恥ずかしがり屋で内気な性格で話してください。"
    
    energetic:
      name: "元気"
      prompt_modifier: "とても元気で活発な性格で話してください。"
    
    calm:
      name: "落ち着いた"
      prompt_modifier: "落ち着いていて知的な印象で話してください。"

# Audio Settings
audio_settings:
  sample_rate: 16000
  chunk_size: 1024
  format: "wav"
  
  voice_settings:
    default_speaker: 0
    noise_scale: 0.667
    noise_scale_w: 0.8
    length_scale: 1.0

# Memory Settings
memory_settings:
  conversation_history_limit: 20
  context_window_size: 4000
  enable_user_info_tracking: true

# Performance Settings
performance:
  max_response_time_ms: 500
  retry_attempts: 3
  retry_delay_ms: 1000
